worlds:
    new world:
    - 3LSOL1I3I
    - RFIW9GEN4
    - NFUOJ5A0Y
    - 597YGSOFT
    - PEHAOJ1XB
    - T7XKHFGOR
    - CAOBIAUPR
    - DLVTNS5XI
    - QARHRCREX
    - NFKARLYMH
    - 1FYF50LUL
    ruins test:
    - ABMSV59QR
    - CARWT66ZO
    - MAUMH4DR1
