name = "Kakusei-Packwiz"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc3d802eebc070fe4172d0dfb76ddc2511e3839a7ecd6893839f02a2eb0b273c"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
