name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c907df175fb02ed19a9d59fad1c1ed796c73292daeebaae1be00f0d96434ef3f"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
