name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56e08d58c65eadb4dc4826e9e45bb83fe7a83740c7c6c2ffb9a0e19af861e7bd"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
