name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aea3c5991fef0d299ccb34edacb1374550c7bab4e5db11dfbcef3c2935152ff6"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
