name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d70e9482fa2f4e5c8d93d02bccb68a793c73ca05cdb30b9e18ea66dadd1bcc3"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
