name = "Kakusei-Packwiz"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abff93c1b469dafa19e130e5666a551eefc3ba929bb62617c94776030f59abc4"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
