name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aecc8c1befefb218d5b07a5bbe6dc28f9e23f9a25d6177bd874634eae1fb107d"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
