name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92bad4fa793bae0fd075fcc7fa4ee876ae7b5b8c03c486aa02a2cece73b56322"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
