name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6e9e15196b55a4a2be19aceabd726f2de1591d4aa44f21a43cc814a700b8fad"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
