name = "Kakusei-Packwiz"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffa42d7507abbec60387d45e7b54ee5fdb36b0df9fe2dacb006105928bdfde6e"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
