name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a55e51f824cc0d576c564c21d1ceb9dc8217e6b1dbceb21f3f1b143d97b3c9dd"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
