name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c142c22016e8ee89ddc323c5fd7fb00821cbe11e764dc4454bdb1cc6ec38cc3e"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
