name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "957d9b7ac8a3ae7cae8df6eb6bf72126ef3e5692c00d1f4c0abb629d1a87eccc"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
