name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c6d0ea67b40de0bef22b0bdee7cf0476d67e4ff2768daf150d5a46f6dd9cfeb"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
