name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e905186fa1765968177cc70f5bcce27ad1fc1ff4a7b6b9de5fedad483c89ae8"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
