name = "Kakusei-Packwiz"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7547da509b4dc3721ca71449c098a0988faf6d44b1dc698ec990afc2434ff2de"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
