name = "Kakusei-Packwiz"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6abb1a2a69e9f2449accdef5dbc12a58c955797ccbc7310004d9c9abc4e5ab2"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
