name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.660.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/328/CraftTweaker2-1.12-4.1.20.660.jar"
hash-format = "murmur2"
hash = "73977536"

[update]
[update.curseforge]
file-id = 3435328
project-id = 239197
release-channel = "beta"
