name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.603.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3130/347/CraftTweaker2-1.12-4.1.20.603.jar"
hash-format = "murmur2"
hash = "1097745532"

[update]
[update.curseforge]
file-id = 3130347
project-id = 239197
release-channel = "beta"
