name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.655.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3383/242/CraftTweaker2-1.12-4.1.20.655.jar"
hash-format = "murmur2"
hash = "156829327"

[update]
[update.curseforge]
file-id = 3383242
project-id = 239197
release-channel = "beta"
