name = "Discord Integration Forge"
filename = "dcintegration-forge-2.2.0-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3352/30/dcintegration-forge-2.2.0-1.12.jar"
hash-format = "murmur2"
hash = "1219521910"

[update]
[update.curseforge]
file-id = 3352030
project-id = 324952
release-channel = "beta"
