name = "Ender IO"
filename = "EnderIO-1.12.2-5.3.68.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3325/806/EnderIO-1.12.2-5.3.68.jar"
hash-format = "murmur2"
hash = "2650911804"

[update]
[update.curseforge]
file-id = 3325806
project-id = 64578
release-channel = "beta"
