name = "Foam​Fix"
filename = "foamfix-0.10.12-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3319/39/foamfix-0.10.12-1.12.2.jar"
hash-format = "murmur2"
hash = "2372015121"

[update]
[update.curseforge]
file-id = 3319039
project-id = 278494
release-channel = "beta"
