name = "Foam​Fix"
filename = "foamfix-0.10.12a-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3319/452/foamfix-0.10.12a-1.12.2.jar"
hash-format = "murmur2"
hash = "4075342327"

[update]
[update.curseforge]
file-id = 3319452
project-id = 278494
release-channel = "beta"
