name = "LittleTiles"
filename = "LittleTiles_v1.5.21_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3445/700/LittleTiles_v1.5.21_mc1.12.2.jar"
hash-format = "murmur2"
hash = "1450356025"

[update]
[update.curseforge]
file-id = 3445700
project-id = 257818
release-channel = "beta"
