name = "Lucraft: Core"
filename = "LucraftCore-1.12.2-2.4.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3283/571/LucraftCore-1.12.2-2.4.14.jar"
hash-format = "murmur2"
hash = "3304371275"

[update]
[update.curseforge]
file-id = 3283571
project-id = 230651
release-channel = "beta"
