name = "Prefab"
filename = "prefab-1.3.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3356/960/prefab-1.3.1.1.jar"
hash-format = "murmur2"
hash = "1026888655"

[update]
[update.curseforge]
file-id = 3356960
project-id = 246550
release-channel = "beta"
