name = "U Team Core"
filename = "u_team_core-1.12.2-2.2.5.147.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2873/110/u_team_core-1.12.2-2.2.5.147.jar"
hash-format = "murmur2"
hash = "404974864"

[update]
[update.curseforge]
file-id = 2873110
project-id = 273744
release-channel = "beta"
