name = "UniDict"
filename = "UniDict-1.12.2-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3130/345/UniDict-1.12.2-3.0.0.jar"
hash-format = "murmur2"
hash = "1398379019"

[update]
[update.curseforge]
file-id = 3130345
project-id = 244258
release-channel = "beta"
