name = "WanionLib"
filename = "WanionLib-1.12.2-2.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/911/WanionLib-1.12.2-2.8.jar"
hash-format = "murmur2"
hash = "244550551"

[update]
[update.curseforge]
file-id = 3577911
project-id = 253043
release-channel = "beta"
